server:
  port: 8080

spring:
  session:
    store-type: redis

  data:
    redis:
      host: redis-service
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      probes:
        enabled: true